---
version: 2
updates:
  - package-ecosystem: gomod
    directory: '/'
    labels: ["dependencies"]
    schedule:
      interval: 'daily'
    commit-message:
      prefix: "chore"
      
  - package-ecosystem: 'github-actions'
    directory: '/'
    labels: ["dependencies"]
    schedule:
      interval: 'daily'
    commit-message:
      prefix: "chore"
    groups:
      github:
        update-types:
          - 'minor'
          - 'patch'
          

