# Linter selection and configuration file for golangci-lint.
linters:
  # Disable all linters. It's important to have reproducible CI: don't start to fail all builds at the same time.
  # With golangci-lint this can happen if you use option --enable-all and a new linter is added
  # or when one upstream linter is upgraded.
  # Default: false
  disable-all: true
  # Enable specific linter
  # If linters should be disabled, comment out the respective line with explaination.
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    #- depguard - no package black list needed for now
    - dogsled
    - dupl
    - dupword
    - durationcheck
    #- err113 - enable after refactoring
    - errcheck
    - errchkjson
    - errname
    #- errorlint - enable after refactoring
    # - execinquery - deprecated
    #- exhaustive - It's ok not not set every field in a struct
    #- exhaustruct - It's ok not not set every field in a struct
    - exportloopref
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    #- gofumpt - no idea what format it checks, output is not helpful
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    #- paralleltest - Not necessary to do parallel tests for now, might enable later again
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    #- testpackage - We don't enforce white box testing
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    #- wrapcheck - Not ALL error should be wrapped, as they become part of the function API then.
    - wsl
    - zerologlint

# Options for analysis running.
run:
  # Include test files or not.
  # Default: true
  tests: false

# Settings of specific linters.
linters-settings:
  varnamelen:
    max-distance: 6
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
      - wg # WaitGroup
      - s # Session
      - ch # Channel
      - tt # Test Table
      - r # Reader

