---
version: '3'

includes:
  misc:
    taskfile: ./.firmwareci/Taskfile.yml
    dir: ./.firmwareci
    optional: true
    vars:
      FWCI_PROJECT_NAME: "test-dutctl"
      DUTCTL_CONFIG_FILE: "/etc/dutctl.yaml"
      SYSTEMD_FILE: "dutagent.service"
