---
version: 1.0.0-alpha.1 # x-release-please-version
devices:
  device2:
    desc: "Device 2"
    cmds:
      status:
        desc: "Report status"
        uses:
          - module: dummy-status
            passthrough: true
      repeat:
        desc: "Repeat input"
        uses:
          - module: dummy-repeat
            passthrough: true
