---
version: 1.0.0-alpha.1 # x-release-please-version
devices:
  device1:
    desc: "Device 1"
    cmds:
      status:
        desc: "Report status"
        uses:
          - module: dummy-status
            passthrough: true
